export {
    mdiCloseCircleOutline as closeCircleOutline,
    mdiBrightness6 as brightness6,
    mdiCreationOutline as creationOutline,
    mdiLightbulb as lightbulb,
    mdiLightbulbOff as lightbulbOff,
    mdiLightbulbGroupOff as lightbulbGroupOff,
    mdiLightbulbGroup as lightbulbGroup,
    mdiSnowflake as snowflake,
    mdiFire as fire,
    mdiPower as power,
    mdiExclamation as exclamation,
    mdiSlashForward as slash,
    mdiMinus as minus,
    mdiPlus as plus,
    mdiThermometer as thermometer,
    mdiArrowDownThin as minimum,
    mdiFan as fan,
    mdiArrowUpThin as maximum,
    mdiVolumeHigh as volume,
    mdiVolumeOff as volumeOff,

} from '@mdi/js';